{{- if eq .Values.policies.enabled true }}
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequiredLabels
metadata:
  name: app-label-on-pods-{{ trunc 8 (print .Release.Name  "-" .Release.Namespace | sha1sum) }}
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
    namespaces:
    - {{ .Release.Namespace }}
  parameters:
    labels: ["app"]
{{- end }}